// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: device_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from device_messages.proto</summary>
public static partial class DeviceMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for device_messages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DeviceMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVkZXZpY2VfbWVzc2FnZXMucHJvdG8iSAoHVmVyc2lvbhINCgVNYWpvchgB",
          "IAEoDRINCgVNaW5vchgCIAEoDRINCgVQYXRjaBgDIAEoDRIQCghSZXZpc2lv",
          "bhgEIAEoDSIxCghEZXZpY2VJZBILCgNJZDAYASABKA0SCwoDSWQxGAIgASgN",
          "EgsKA0lkMhgDIAEoDSKuAQoLTG9yYVJlY2VpdmUSDAoEU2l6ZRgBIAEoDRIM",
          "CgRSc3NpGAIgASgNEgsKA1NuchgDIAEoDRIWCg5TZXF1ZW5jZU51bWJlchgE",
          "IAEoDRIiChVJc01lYXN1cmVtZW50RnJhZ21lbnQYBSABKAhIAIgBARIPCgdT",
          "dWNjZXNzGAYgASgIEg8KB1BheWxvYWQYByABKAxCGAoWX0lzTWVhc3VyZW1l",
          "bnRGcmFnbWVudCJmCgtCb290TWVzc2FnZRIjChBEZXZpY2VJZGVudGlmaWVy",
          "GAEgASgLMgkuRGV2aWNlSWQSIQoPRmlybXdhcmVWZXJzaW9uGAIgASgLMggu",
          "VmVyc2lvbhIPCgdBcHBOYW1lGAMgASgJIiQKCkFja01lc3NhZ2USFgoOU2Vx",
          "dWVuY2VOdW1iZXIYASABKA0iigEKDFVhcnRSZXNwb25zZRIjCgtib290TWVz",
          "c2FnZRgBIAEoCzIMLkJvb3RNZXNzYWdlSAASIQoKYWNrTWVzc2FnZRgCIAEo",
          "CzILLkFja01lc3NhZ2VIABIqChJsb3JhUmVjZWl2ZU1lc3NhZ2UYAyABKAsy",
          "DC5Mb3JhUmVjZWl2ZUgAQgYKBEJvZHkiTQoVU3ByZWFkaW5nRmFjdG9yQ29u",
          "ZmlnEhkKEXNwcmVhZGluZ0ZhY3RvclJ4GAEgASgNEhkKEXNwcmVhZGluZ0Zh",
          "Y3RvclR4GAIgASgNIlEKFVNlcXVlbmNlUmVxdWVzdENvbmZpZxIUCgxNZXNz",
          "YWdlQ291bnQYASABKA0SEAoISW50ZXJ2YWwYAiABKA0SEAoIRGV2aWNlSWQY",
          "AyABKA0iqwMKC0xvUmFNZXNzYWdlEikKB2NvbW1hbmQYASABKA4yGC5Mb1Jh",
          "TWVzc2FnZS5Db21tYW5kVHlwZRIWCg5TZXF1ZW5jZU51bWJlchgCIAEoDRI3",
          "ChVzcHJlYWRpbmdGYWN0b3JDb25maWcYAyABKAsyFi5TcHJlYWRpbmdGYWN0",
          "b3JDb25maWdIABI3ChVzZXF1ZW5jZVJlcXVlc3RDb25maWcYBCABKAsyFi5T",
          "ZXF1ZW5jZVJlcXVlc3RDb25maWdIABIRCgdwYXlsb2FkGAUgASgMSAAiywEK",
          "C0NvbW1hbmRUeXBlEhEKDUNvbmZpZ3VyYXRpb24QABINCglNdWx0aUNhc3QQ",
          "ARIQCgxNdWx0aUNhc3RBY2sQAhILCgdVbmlDYXN0EAMSDgoKVW5pQ2FzdEFj",
          "axAEEhwKGE1lYXN1cmVtZW50U3RyZWFtUmVxdWVzdBAFEiIKHk1lYXN1cmVt",
          "ZW50U3RyZWFtRnJhZ21lbnRSZXBseRAGEhMKD1NlcXVlbmNlUmVxdWVzdBAH",
          "EhQKEFNlcXVlbmNlUmVzcG9uc2UQCEIGCgRCb2R5YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Version), global::Version.Parser, new[]{ "Major", "Minor", "Patch", "Revision" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DeviceId), global::DeviceId.Parser, new[]{ "Id0", "Id1", "Id2" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoraReceive), global::LoraReceive.Parser, new[]{ "Size", "Rssi", "Snr", "SequenceNumber", "IsMeasurementFragment", "Success", "Payload" }, new[]{ "IsMeasurementFragment" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BootMessage), global::BootMessage.Parser, new[]{ "DeviceIdentifier", "FirmwareVersion", "AppName" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AckMessage), global::AckMessage.Parser, new[]{ "SequenceNumber" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UartResponse), global::UartResponse.Parser, new[]{ "BootMessage", "AckMessage", "LoraReceiveMessage" }, new[]{ "Body" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SpreadingFactorConfig), global::SpreadingFactorConfig.Parser, new[]{ "SpreadingFactorRx", "SpreadingFactorTx" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SequenceRequestConfig), global::SequenceRequestConfig.Parser, new[]{ "MessageCount", "Interval", "DeviceId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoRaMessage), global::LoRaMessage.Parser, new[]{ "Command", "SequenceNumber", "SpreadingFactorConfig", "SequenceRequestConfig", "Payload" }, new[]{ "Body" }, new[]{ typeof(global::LoRaMessage.Types.CommandType) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Version : pb::IMessage<Version>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Version> _parser = new pb::MessageParser<Version>(() => new Version());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Version> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version(Version other) : this() {
    major_ = other.major_;
    minor_ = other.minor_;
    patch_ = other.patch_;
    revision_ = other.revision_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version Clone() {
    return new Version(this);
  }

  /// <summary>Field number for the "Major" field.</summary>
  public const int MajorFieldNumber = 1;
  private uint major_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Major {
    get { return major_; }
    set {
      major_ = value;
    }
  }

  /// <summary>Field number for the "Minor" field.</summary>
  public const int MinorFieldNumber = 2;
  private uint minor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Minor {
    get { return minor_; }
    set {
      minor_ = value;
    }
  }

  /// <summary>Field number for the "Patch" field.</summary>
  public const int PatchFieldNumber = 3;
  private uint patch_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Patch {
    get { return patch_; }
    set {
      patch_ = value;
    }
  }

  /// <summary>Field number for the "Revision" field.</summary>
  public const int RevisionFieldNumber = 4;
  private uint revision_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Revision {
    get { return revision_; }
    set {
      revision_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Version);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Version other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Major != other.Major) return false;
    if (Minor != other.Minor) return false;
    if (Patch != other.Patch) return false;
    if (Revision != other.Revision) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Major != 0) hash ^= Major.GetHashCode();
    if (Minor != 0) hash ^= Minor.GetHashCode();
    if (Patch != 0) hash ^= Patch.GetHashCode();
    if (Revision != 0) hash ^= Revision.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Major != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Major);
    }
    if (Minor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Minor);
    }
    if (Patch != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Patch);
    }
    if (Revision != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Revision);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Major != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Major);
    }
    if (Minor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Minor);
    }
    if (Patch != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Patch);
    }
    if (Revision != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Revision);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Major != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Major);
    }
    if (Minor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Minor);
    }
    if (Patch != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Patch);
    }
    if (Revision != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Revision);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Version other) {
    if (other == null) {
      return;
    }
    if (other.Major != 0) {
      Major = other.Major;
    }
    if (other.Minor != 0) {
      Minor = other.Minor;
    }
    if (other.Patch != 0) {
      Patch = other.Patch;
    }
    if (other.Revision != 0) {
      Revision = other.Revision;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Major = input.ReadUInt32();
          break;
        }
        case 16: {
          Minor = input.ReadUInt32();
          break;
        }
        case 24: {
          Patch = input.ReadUInt32();
          break;
        }
        case 32: {
          Revision = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Major = input.ReadUInt32();
          break;
        }
        case 16: {
          Minor = input.ReadUInt32();
          break;
        }
        case 24: {
          Patch = input.ReadUInt32();
          break;
        }
        case 32: {
          Revision = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DeviceId : pb::IMessage<DeviceId>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DeviceId> _parser = new pb::MessageParser<DeviceId>(() => new DeviceId());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DeviceId> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId(DeviceId other) : this() {
    id0_ = other.id0_;
    id1_ = other.id1_;
    id2_ = other.id2_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId Clone() {
    return new DeviceId(this);
  }

  /// <summary>Field number for the "Id0" field.</summary>
  public const int Id0FieldNumber = 1;
  private uint id0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id0 {
    get { return id0_; }
    set {
      id0_ = value;
    }
  }

  /// <summary>Field number for the "Id1" field.</summary>
  public const int Id1FieldNumber = 2;
  private uint id1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id1 {
    get { return id1_; }
    set {
      id1_ = value;
    }
  }

  /// <summary>Field number for the "Id2" field.</summary>
  public const int Id2FieldNumber = 3;
  private uint id2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id2 {
    get { return id2_; }
    set {
      id2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DeviceId);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DeviceId other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id0 != other.Id0) return false;
    if (Id1 != other.Id1) return false;
    if (Id2 != other.Id2) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id0 != 0) hash ^= Id0.GetHashCode();
    if (Id1 != 0) hash ^= Id1.GetHashCode();
    if (Id2 != 0) hash ^= Id2.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id0 != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id0);
    }
    if (Id1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id1);
    }
    if (Id2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Id2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id0 != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id0);
    }
    if (Id1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id1);
    }
    if (Id2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Id2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id0 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id0);
    }
    if (Id1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id1);
    }
    if (Id2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id2);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DeviceId other) {
    if (other == null) {
      return;
    }
    if (other.Id0 != 0) {
      Id0 = other.Id0;
    }
    if (other.Id1 != 0) {
      Id1 = other.Id1;
    }
    if (other.Id2 != 0) {
      Id2 = other.Id2;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id0 = input.ReadUInt32();
          break;
        }
        case 16: {
          Id1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Id2 = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id0 = input.ReadUInt32();
          break;
        }
        case 16: {
          Id1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Id2 = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LoraReceive : pb::IMessage<LoraReceive>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoraReceive> _parser = new pb::MessageParser<LoraReceive>(() => new LoraReceive());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoraReceive> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive(LoraReceive other) : this() {
    _hasBits0 = other._hasBits0;
    size_ = other.size_;
    rssi_ = other.rssi_;
    snr_ = other.snr_;
    sequenceNumber_ = other.sequenceNumber_;
    isMeasurementFragment_ = other.isMeasurementFragment_;
    success_ = other.success_;
    payload_ = other.payload_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive Clone() {
    return new LoraReceive(this);
  }

  /// <summary>Field number for the "Size" field.</summary>
  public const int SizeFieldNumber = 1;
  private uint size_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Size {
    get { return size_; }
    set {
      size_ = value;
    }
  }

  /// <summary>Field number for the "Rssi" field.</summary>
  public const int RssiFieldNumber = 2;
  private uint rssi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Rssi {
    get { return rssi_; }
    set {
      rssi_ = value;
    }
  }

  /// <summary>Field number for the "Snr" field.</summary>
  public const int SnrFieldNumber = 3;
  private uint snr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Snr {
    get { return snr_; }
    set {
      snr_ = value;
    }
  }

  /// <summary>Field number for the "SequenceNumber" field.</summary>
  public const int SequenceNumberFieldNumber = 4;
  private uint sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  /// <summary>Field number for the "IsMeasurementFragment" field.</summary>
  public const int IsMeasurementFragmentFieldNumber = 5;
  private bool isMeasurementFragment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsMeasurementFragment {
    get { if ((_hasBits0 & 1) != 0) { return isMeasurementFragment_; } else { return false; } }
    set {
      _hasBits0 |= 1;
      isMeasurementFragment_ = value;
    }
  }
  /// <summary>Gets whether the "IsMeasurementFragment" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIsMeasurementFragment {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "IsMeasurementFragment" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIsMeasurementFragment() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Success" field.</summary>
  public const int SuccessFieldNumber = 6;
  private bool success_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Success {
    get { return success_; }
    set {
      success_ = value;
    }
  }

  /// <summary>Field number for the "Payload" field.</summary>
  public const int PayloadFieldNumber = 7;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoraReceive);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoraReceive other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Size != other.Size) return false;
    if (Rssi != other.Rssi) return false;
    if (Snr != other.Snr) return false;
    if (SequenceNumber != other.SequenceNumber) return false;
    if (IsMeasurementFragment != other.IsMeasurementFragment) return false;
    if (Success != other.Success) return false;
    if (Payload != other.Payload) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Size != 0) hash ^= Size.GetHashCode();
    if (Rssi != 0) hash ^= Rssi.GetHashCode();
    if (Snr != 0) hash ^= Snr.GetHashCode();
    if (SequenceNumber != 0) hash ^= SequenceNumber.GetHashCode();
    if (HasIsMeasurementFragment) hash ^= IsMeasurementFragment.GetHashCode();
    if (Success != false) hash ^= Success.GetHashCode();
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Size != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Size);
    }
    if (Rssi != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Rssi);
    }
    if (Snr != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Snr);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      output.WriteRawTag(40);
      output.WriteBool(IsMeasurementFragment);
    }
    if (Success != false) {
      output.WriteRawTag(48);
      output.WriteBool(Success);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Size != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Size);
    }
    if (Rssi != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Rssi);
    }
    if (Snr != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Snr);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      output.WriteRawTag(40);
      output.WriteBool(IsMeasurementFragment);
    }
    if (Success != false) {
      output.WriteRawTag(48);
      output.WriteBool(Success);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Size != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Size);
    }
    if (Rssi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rssi);
    }
    if (Snr != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Snr);
    }
    if (SequenceNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      size += 1 + 1;
    }
    if (Success != false) {
      size += 1 + 1;
    }
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoraReceive other) {
    if (other == null) {
      return;
    }
    if (other.Size != 0) {
      Size = other.Size;
    }
    if (other.Rssi != 0) {
      Rssi = other.Rssi;
    }
    if (other.Snr != 0) {
      Snr = other.Snr;
    }
    if (other.SequenceNumber != 0) {
      SequenceNumber = other.SequenceNumber;
    }
    if (other.HasIsMeasurementFragment) {
      IsMeasurementFragment = other.IsMeasurementFragment;
    }
    if (other.Success != false) {
      Success = other.Success;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Size = input.ReadUInt32();
          break;
        }
        case 16: {
          Rssi = input.ReadUInt32();
          break;
        }
        case 24: {
          Snr = input.ReadUInt32();
          break;
        }
        case 32: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 40: {
          IsMeasurementFragment = input.ReadBool();
          break;
        }
        case 48: {
          Success = input.ReadBool();
          break;
        }
        case 58: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Size = input.ReadUInt32();
          break;
        }
        case 16: {
          Rssi = input.ReadUInt32();
          break;
        }
        case 24: {
          Snr = input.ReadUInt32();
          break;
        }
        case 32: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 40: {
          IsMeasurementFragment = input.ReadBool();
          break;
        }
        case 48: {
          Success = input.ReadBool();
          break;
        }
        case 58: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class BootMessage : pb::IMessage<BootMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BootMessage> _parser = new pb::MessageParser<BootMessage>(() => new BootMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BootMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage(BootMessage other) : this() {
    deviceIdentifier_ = other.deviceIdentifier_ != null ? other.deviceIdentifier_.Clone() : null;
    firmwareVersion_ = other.firmwareVersion_ != null ? other.firmwareVersion_.Clone() : null;
    appName_ = other.appName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage Clone() {
    return new BootMessage(this);
  }

  /// <summary>Field number for the "DeviceIdentifier" field.</summary>
  public const int DeviceIdentifierFieldNumber = 1;
  private global::DeviceId deviceIdentifier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DeviceId DeviceIdentifier {
    get { return deviceIdentifier_; }
    set {
      deviceIdentifier_ = value;
    }
  }

  /// <summary>Field number for the "FirmwareVersion" field.</summary>
  public const int FirmwareVersionFieldNumber = 2;
  private global::Version firmwareVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Version FirmwareVersion {
    get { return firmwareVersion_; }
    set {
      firmwareVersion_ = value;
    }
  }

  /// <summary>Field number for the "AppName" field.</summary>
  public const int AppNameFieldNumber = 3;
  private string appName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppName {
    get { return appName_; }
    set {
      appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BootMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BootMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DeviceIdentifier, other.DeviceIdentifier)) return false;
    if (!object.Equals(FirmwareVersion, other.FirmwareVersion)) return false;
    if (AppName != other.AppName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (deviceIdentifier_ != null) hash ^= DeviceIdentifier.GetHashCode();
    if (firmwareVersion_ != null) hash ^= FirmwareVersion.GetHashCode();
    if (AppName.Length != 0) hash ^= AppName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (deviceIdentifier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AppName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (deviceIdentifier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AppName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (deviceIdentifier_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BootMessage other) {
    if (other == null) {
      return;
    }
    if (other.deviceIdentifier_ != null) {
      if (deviceIdentifier_ == null) {
        DeviceIdentifier = new global::DeviceId();
      }
      DeviceIdentifier.MergeFrom(other.DeviceIdentifier);
    }
    if (other.firmwareVersion_ != null) {
      if (firmwareVersion_ == null) {
        FirmwareVersion = new global::Version();
      }
      FirmwareVersion.MergeFrom(other.FirmwareVersion);
    }
    if (other.AppName.Length != 0) {
      AppName = other.AppName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (deviceIdentifier_ == null) {
            DeviceIdentifier = new global::DeviceId();
          }
          input.ReadMessage(DeviceIdentifier);
          break;
        }
        case 18: {
          if (firmwareVersion_ == null) {
            FirmwareVersion = new global::Version();
          }
          input.ReadMessage(FirmwareVersion);
          break;
        }
        case 26: {
          AppName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (deviceIdentifier_ == null) {
            DeviceIdentifier = new global::DeviceId();
          }
          input.ReadMessage(DeviceIdentifier);
          break;
        }
        case 18: {
          if (firmwareVersion_ == null) {
            FirmwareVersion = new global::Version();
          }
          input.ReadMessage(FirmwareVersion);
          break;
        }
        case 26: {
          AppName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class AckMessage : pb::IMessage<AckMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AckMessage> _parser = new pb::MessageParser<AckMessage>(() => new AckMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AckMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage(AckMessage other) : this() {
    sequenceNumber_ = other.sequenceNumber_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage Clone() {
    return new AckMessage(this);
  }

  /// <summary>Field number for the "SequenceNumber" field.</summary>
  public const int SequenceNumberFieldNumber = 1;
  private uint sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AckMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AckMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SequenceNumber != other.SequenceNumber) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SequenceNumber != 0) hash ^= SequenceNumber.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SequenceNumber != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SequenceNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SequenceNumber != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SequenceNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SequenceNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNumber);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AckMessage other) {
    if (other == null) {
      return;
    }
    if (other.SequenceNumber != 0) {
      SequenceNumber = other.SequenceNumber;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class UartResponse : pb::IMessage<UartResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UartResponse> _parser = new pb::MessageParser<UartResponse>(() => new UartResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UartResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse(UartResponse other) : this() {
    switch (other.BodyCase) {
      case BodyOneofCase.BootMessage:
        BootMessage = other.BootMessage.Clone();
        break;
      case BodyOneofCase.AckMessage:
        AckMessage = other.AckMessage.Clone();
        break;
      case BodyOneofCase.LoraReceiveMessage:
        LoraReceiveMessage = other.LoraReceiveMessage.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse Clone() {
    return new UartResponse(this);
  }

  /// <summary>Field number for the "bootMessage" field.</summary>
  public const int BootMessageFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::BootMessage BootMessage {
    get { return bodyCase_ == BodyOneofCase.BootMessage ? (global::BootMessage) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.BootMessage;
    }
  }

  /// <summary>Field number for the "ackMessage" field.</summary>
  public const int AckMessageFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AckMessage AckMessage {
    get { return bodyCase_ == BodyOneofCase.AckMessage ? (global::AckMessage) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.AckMessage;
    }
  }

  /// <summary>Field number for the "loraReceiveMessage" field.</summary>
  public const int LoraReceiveMessageFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LoraReceive LoraReceiveMessage {
    get { return bodyCase_ == BodyOneofCase.LoraReceiveMessage ? (global::LoraReceive) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.LoraReceiveMessage;
    }
  }

  private object body_;
  /// <summary>Enum of possible cases for the "Body" oneof.</summary>
  public enum BodyOneofCase {
    None = 0,
    BootMessage = 1,
    AckMessage = 2,
    LoraReceiveMessage = 3,
  }
  private BodyOneofCase bodyCase_ = BodyOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BodyOneofCase BodyCase {
    get { return bodyCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBody() {
    bodyCase_ = BodyOneofCase.None;
    body_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UartResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UartResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(BootMessage, other.BootMessage)) return false;
    if (!object.Equals(AckMessage, other.AckMessage)) return false;
    if (!object.Equals(LoraReceiveMessage, other.LoraReceiveMessage)) return false;
    if (BodyCase != other.BodyCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (bodyCase_ == BodyOneofCase.BootMessage) hash ^= BootMessage.GetHashCode();
    if (bodyCase_ == BodyOneofCase.AckMessage) hash ^= AckMessage.GetHashCode();
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) hash ^= LoraReceiveMessage.GetHashCode();
    hash ^= (int) bodyCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      output.WriteRawTag(10);
      output.WriteMessage(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      output.WriteRawTag(18);
      output.WriteMessage(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      output.WriteRawTag(26);
      output.WriteMessage(LoraReceiveMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      output.WriteRawTag(10);
      output.WriteMessage(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      output.WriteRawTag(18);
      output.WriteMessage(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      output.WriteRawTag(26);
      output.WriteMessage(LoraReceiveMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoraReceiveMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UartResponse other) {
    if (other == null) {
      return;
    }
    switch (other.BodyCase) {
      case BodyOneofCase.BootMessage:
        if (BootMessage == null) {
          BootMessage = new global::BootMessage();
        }
        BootMessage.MergeFrom(other.BootMessage);
        break;
      case BodyOneofCase.AckMessage:
        if (AckMessage == null) {
          AckMessage = new global::AckMessage();
        }
        AckMessage.MergeFrom(other.AckMessage);
        break;
      case BodyOneofCase.LoraReceiveMessage:
        if (LoraReceiveMessage == null) {
          LoraReceiveMessage = new global::LoraReceive();
        }
        LoraReceiveMessage.MergeFrom(other.LoraReceiveMessage);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::BootMessage subBuilder = new global::BootMessage();
          if (bodyCase_ == BodyOneofCase.BootMessage) {
            subBuilder.MergeFrom(BootMessage);
          }
          input.ReadMessage(subBuilder);
          BootMessage = subBuilder;
          break;
        }
        case 18: {
          global::AckMessage subBuilder = new global::AckMessage();
          if (bodyCase_ == BodyOneofCase.AckMessage) {
            subBuilder.MergeFrom(AckMessage);
          }
          input.ReadMessage(subBuilder);
          AckMessage = subBuilder;
          break;
        }
        case 26: {
          global::LoraReceive subBuilder = new global::LoraReceive();
          if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
            subBuilder.MergeFrom(LoraReceiveMessage);
          }
          input.ReadMessage(subBuilder);
          LoraReceiveMessage = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::BootMessage subBuilder = new global::BootMessage();
          if (bodyCase_ == BodyOneofCase.BootMessage) {
            subBuilder.MergeFrom(BootMessage);
          }
          input.ReadMessage(subBuilder);
          BootMessage = subBuilder;
          break;
        }
        case 18: {
          global::AckMessage subBuilder = new global::AckMessage();
          if (bodyCase_ == BodyOneofCase.AckMessage) {
            subBuilder.MergeFrom(AckMessage);
          }
          input.ReadMessage(subBuilder);
          AckMessage = subBuilder;
          break;
        }
        case 26: {
          global::LoraReceive subBuilder = new global::LoraReceive();
          if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
            subBuilder.MergeFrom(LoraReceiveMessage);
          }
          input.ReadMessage(subBuilder);
          LoraReceiveMessage = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SpreadingFactorConfig : pb::IMessage<SpreadingFactorConfig>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SpreadingFactorConfig> _parser = new pb::MessageParser<SpreadingFactorConfig>(() => new SpreadingFactorConfig());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SpreadingFactorConfig> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpreadingFactorConfig() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpreadingFactorConfig(SpreadingFactorConfig other) : this() {
    spreadingFactorRx_ = other.spreadingFactorRx_;
    spreadingFactorTx_ = other.spreadingFactorTx_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpreadingFactorConfig Clone() {
    return new SpreadingFactorConfig(this);
  }

  /// <summary>Field number for the "spreadingFactorRx" field.</summary>
  public const int SpreadingFactorRxFieldNumber = 1;
  private uint spreadingFactorRx_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SpreadingFactorRx {
    get { return spreadingFactorRx_; }
    set {
      spreadingFactorRx_ = value;
    }
  }

  /// <summary>Field number for the "spreadingFactorTx" field.</summary>
  public const int SpreadingFactorTxFieldNumber = 2;
  private uint spreadingFactorTx_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SpreadingFactorTx {
    get { return spreadingFactorTx_; }
    set {
      spreadingFactorTx_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SpreadingFactorConfig);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SpreadingFactorConfig other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SpreadingFactorRx != other.SpreadingFactorRx) return false;
    if (SpreadingFactorTx != other.SpreadingFactorTx) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SpreadingFactorRx != 0) hash ^= SpreadingFactorRx.GetHashCode();
    if (SpreadingFactorTx != 0) hash ^= SpreadingFactorTx.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SpreadingFactorRx != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SpreadingFactorRx);
    }
    if (SpreadingFactorTx != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(SpreadingFactorTx);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SpreadingFactorRx != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SpreadingFactorRx);
    }
    if (SpreadingFactorTx != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(SpreadingFactorTx);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SpreadingFactorRx != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpreadingFactorRx);
    }
    if (SpreadingFactorTx != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpreadingFactorTx);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SpreadingFactorConfig other) {
    if (other == null) {
      return;
    }
    if (other.SpreadingFactorRx != 0) {
      SpreadingFactorRx = other.SpreadingFactorRx;
    }
    if (other.SpreadingFactorTx != 0) {
      SpreadingFactorTx = other.SpreadingFactorTx;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SpreadingFactorRx = input.ReadUInt32();
          break;
        }
        case 16: {
          SpreadingFactorTx = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SpreadingFactorRx = input.ReadUInt32();
          break;
        }
        case 16: {
          SpreadingFactorTx = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SequenceRequestConfig : pb::IMessage<SequenceRequestConfig>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SequenceRequestConfig> _parser = new pb::MessageParser<SequenceRequestConfig>(() => new SequenceRequestConfig());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SequenceRequestConfig> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SequenceRequestConfig() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SequenceRequestConfig(SequenceRequestConfig other) : this() {
    messageCount_ = other.messageCount_;
    interval_ = other.interval_;
    deviceId_ = other.deviceId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SequenceRequestConfig Clone() {
    return new SequenceRequestConfig(this);
  }

  /// <summary>Field number for the "MessageCount" field.</summary>
  public const int MessageCountFieldNumber = 1;
  private uint messageCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MessageCount {
    get { return messageCount_; }
    set {
      messageCount_ = value;
    }
  }

  /// <summary>Field number for the "Interval" field.</summary>
  public const int IntervalFieldNumber = 2;
  private uint interval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Interval {
    get { return interval_; }
    set {
      interval_ = value;
    }
  }

  /// <summary>Field number for the "DeviceId" field.</summary>
  public const int DeviceIdFieldNumber = 3;
  private uint deviceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DeviceId {
    get { return deviceId_; }
    set {
      deviceId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SequenceRequestConfig);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SequenceRequestConfig other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MessageCount != other.MessageCount) return false;
    if (Interval != other.Interval) return false;
    if (DeviceId != other.DeviceId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MessageCount != 0) hash ^= MessageCount.GetHashCode();
    if (Interval != 0) hash ^= Interval.GetHashCode();
    if (DeviceId != 0) hash ^= DeviceId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MessageCount != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(MessageCount);
    }
    if (Interval != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Interval);
    }
    if (DeviceId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(DeviceId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MessageCount != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(MessageCount);
    }
    if (Interval != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Interval);
    }
    if (DeviceId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(DeviceId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MessageCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MessageCount);
    }
    if (Interval != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Interval);
    }
    if (DeviceId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeviceId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SequenceRequestConfig other) {
    if (other == null) {
      return;
    }
    if (other.MessageCount != 0) {
      MessageCount = other.MessageCount;
    }
    if (other.Interval != 0) {
      Interval = other.Interval;
    }
    if (other.DeviceId != 0) {
      DeviceId = other.DeviceId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MessageCount = input.ReadUInt32();
          break;
        }
        case 16: {
          Interval = input.ReadUInt32();
          break;
        }
        case 24: {
          DeviceId = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MessageCount = input.ReadUInt32();
          break;
        }
        case 16: {
          Interval = input.ReadUInt32();
          break;
        }
        case 24: {
          DeviceId = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LoRaMessage : pb::IMessage<LoRaMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoRaMessage> _parser = new pb::MessageParser<LoRaMessage>(() => new LoRaMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoRaMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoRaMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoRaMessage(LoRaMessage other) : this() {
    command_ = other.command_;
    sequenceNumber_ = other.sequenceNumber_;
    switch (other.BodyCase) {
      case BodyOneofCase.SpreadingFactorConfig:
        SpreadingFactorConfig = other.SpreadingFactorConfig.Clone();
        break;
      case BodyOneofCase.SequenceRequestConfig:
        SequenceRequestConfig = other.SequenceRequestConfig.Clone();
        break;
      case BodyOneofCase.Payload:
        Payload = other.Payload;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoRaMessage Clone() {
    return new LoRaMessage(this);
  }

  /// <summary>Field number for the "command" field.</summary>
  public const int CommandFieldNumber = 1;
  private global::LoRaMessage.Types.CommandType command_ = global::LoRaMessage.Types.CommandType.Configuration;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LoRaMessage.Types.CommandType Command {
    get { return command_; }
    set {
      command_ = value;
    }
  }

  /// <summary>Field number for the "SequenceNumber" field.</summary>
  public const int SequenceNumberFieldNumber = 2;
  private uint sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  /// <summary>Field number for the "spreadingFactorConfig" field.</summary>
  public const int SpreadingFactorConfigFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SpreadingFactorConfig SpreadingFactorConfig {
    get { return bodyCase_ == BodyOneofCase.SpreadingFactorConfig ? (global::SpreadingFactorConfig) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.SpreadingFactorConfig;
    }
  }

  /// <summary>Field number for the "sequenceRequestConfig" field.</summary>
  public const int SequenceRequestConfigFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SequenceRequestConfig SequenceRequestConfig {
    get { return bodyCase_ == BodyOneofCase.SequenceRequestConfig ? (global::SequenceRequestConfig) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.SequenceRequestConfig;
    }
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return bodyCase_ == BodyOneofCase.Payload ? (pb::ByteString) body_ : pb::ByteString.Empty; }
    set {
      body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      bodyCase_ = BodyOneofCase.Payload;
    }
  }

  private object body_;
  /// <summary>Enum of possible cases for the "Body" oneof.</summary>
  public enum BodyOneofCase {
    None = 0,
    SpreadingFactorConfig = 3,
    SequenceRequestConfig = 4,
    Payload = 5,
  }
  private BodyOneofCase bodyCase_ = BodyOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BodyOneofCase BodyCase {
    get { return bodyCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBody() {
    bodyCase_ = BodyOneofCase.None;
    body_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoRaMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoRaMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Command != other.Command) return false;
    if (SequenceNumber != other.SequenceNumber) return false;
    if (!object.Equals(SpreadingFactorConfig, other.SpreadingFactorConfig)) return false;
    if (!object.Equals(SequenceRequestConfig, other.SequenceRequestConfig)) return false;
    if (Payload != other.Payload) return false;
    if (BodyCase != other.BodyCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Command != global::LoRaMessage.Types.CommandType.Configuration) hash ^= Command.GetHashCode();
    if (SequenceNumber != 0) hash ^= SequenceNumber.GetHashCode();
    if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) hash ^= SpreadingFactorConfig.GetHashCode();
    if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) hash ^= SequenceRequestConfig.GetHashCode();
    if (bodyCase_ == BodyOneofCase.Payload) hash ^= Payload.GetHashCode();
    hash ^= (int) bodyCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Command != global::LoRaMessage.Types.CommandType.Configuration) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(SequenceNumber);
    }
    if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) {
      output.WriteRawTag(26);
      output.WriteMessage(SpreadingFactorConfig);
    }
    if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) {
      output.WriteRawTag(34);
      output.WriteMessage(SequenceRequestConfig);
    }
    if (bodyCase_ == BodyOneofCase.Payload) {
      output.WriteRawTag(42);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Command != global::LoRaMessage.Types.CommandType.Configuration) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(SequenceNumber);
    }
    if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) {
      output.WriteRawTag(26);
      output.WriteMessage(SpreadingFactorConfig);
    }
    if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) {
      output.WriteRawTag(34);
      output.WriteMessage(SequenceRequestConfig);
    }
    if (bodyCase_ == BodyOneofCase.Payload) {
      output.WriteRawTag(42);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Command != global::LoRaMessage.Types.CommandType.Configuration) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
    }
    if (SequenceNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNumber);
    }
    if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpreadingFactorConfig);
    }
    if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(SequenceRequestConfig);
    }
    if (bodyCase_ == BodyOneofCase.Payload) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoRaMessage other) {
    if (other == null) {
      return;
    }
    if (other.Command != global::LoRaMessage.Types.CommandType.Configuration) {
      Command = other.Command;
    }
    if (other.SequenceNumber != 0) {
      SequenceNumber = other.SequenceNumber;
    }
    switch (other.BodyCase) {
      case BodyOneofCase.SpreadingFactorConfig:
        if (SpreadingFactorConfig == null) {
          SpreadingFactorConfig = new global::SpreadingFactorConfig();
        }
        SpreadingFactorConfig.MergeFrom(other.SpreadingFactorConfig);
        break;
      case BodyOneofCase.SequenceRequestConfig:
        if (SequenceRequestConfig == null) {
          SequenceRequestConfig = new global::SequenceRequestConfig();
        }
        SequenceRequestConfig.MergeFrom(other.SequenceRequestConfig);
        break;
      case BodyOneofCase.Payload:
        Payload = other.Payload;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Command = (global::LoRaMessage.Types.CommandType) input.ReadEnum();
          break;
        }
        case 16: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 26: {
          global::SpreadingFactorConfig subBuilder = new global::SpreadingFactorConfig();
          if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) {
            subBuilder.MergeFrom(SpreadingFactorConfig);
          }
          input.ReadMessage(subBuilder);
          SpreadingFactorConfig = subBuilder;
          break;
        }
        case 34: {
          global::SequenceRequestConfig subBuilder = new global::SequenceRequestConfig();
          if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) {
            subBuilder.MergeFrom(SequenceRequestConfig);
          }
          input.ReadMessage(subBuilder);
          SequenceRequestConfig = subBuilder;
          break;
        }
        case 42: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Command = (global::LoRaMessage.Types.CommandType) input.ReadEnum();
          break;
        }
        case 16: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 26: {
          global::SpreadingFactorConfig subBuilder = new global::SpreadingFactorConfig();
          if (bodyCase_ == BodyOneofCase.SpreadingFactorConfig) {
            subBuilder.MergeFrom(SpreadingFactorConfig);
          }
          input.ReadMessage(subBuilder);
          SpreadingFactorConfig = subBuilder;
          break;
        }
        case 34: {
          global::SequenceRequestConfig subBuilder = new global::SequenceRequestConfig();
          if (bodyCase_ == BodyOneofCase.SequenceRequestConfig) {
            subBuilder.MergeFrom(SequenceRequestConfig);
          }
          input.ReadMessage(subBuilder);
          SequenceRequestConfig = subBuilder;
          break;
        }
        case 42: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the LoRaMessage message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum CommandType {
      [pbr::OriginalName("Configuration")] Configuration = 0,
      [pbr::OriginalName("MultiCast")] MultiCast = 1,
      [pbr::OriginalName("MultiCastAck")] MultiCastAck = 2,
      [pbr::OriginalName("UniCast")] UniCast = 3,
      [pbr::OriginalName("UniCastAck")] UniCastAck = 4,
      [pbr::OriginalName("MeasurementStreamRequest")] MeasurementStreamRequest = 5,
      [pbr::OriginalName("MeasurementStreamFragmentReply")] MeasurementStreamFragmentReply = 6,
      [pbr::OriginalName("SequenceRequest")] SequenceRequest = 7,
      [pbr::OriginalName("SequenceResponse")] SequenceResponse = 8,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
