# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65vice_messages.proto\"H\n\x07Version\x12\r\n\x05Major\x18\x01 \x01(\r\x12\r\n\x05Minor\x18\x02 \x01(\r\x12\r\n\x05Patch\x18\x03 \x01(\r\x12\x10\n\x08Revision\x18\x04 \x01(\r\"1\n\x08\x44\x65viceId\x12\x0b\n\x03Id0\x18\x01 \x01(\r\x12\x0b\n\x03Id1\x18\x02 \x01(\r\x12\x0b\n\x03Id2\x18\x03 \x01(\r\"f\n\x0b\x42ootMessage\x12#\n\x10\x44\x65viceIdentifier\x18\x01 \x01(\x0b\x32\t.DeviceId\x12!\n\x0f\x46irmwareVersion\x18\x02 \x01(\x0b\x32\x08.Version\x12\x0f\n\x07\x41ppName\x18\x03 \x01(\t\";\n\x0cUartResponse\x12#\n\x0b\x62ootMessage\x18\x01 \x01(\x0b\x32\x0c.BootMessageH\x00\x42\x06\n\x04\x42odyb\x06proto3')



_VERSION = DESCRIPTOR.message_types_by_name['Version']
_DEVICEID = DESCRIPTOR.message_types_by_name['DeviceId']
_BOOTMESSAGE = DESCRIPTOR.message_types_by_name['BootMessage']
_UARTRESPONSE = DESCRIPTOR.message_types_by_name['UartResponse']
Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'device_messages_pb2'
  # @@protoc_insertion_point(class_scope:Version)
  })
_sym_db.RegisterMessage(Version)

DeviceId = _reflection.GeneratedProtocolMessageType('DeviceId', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEID,
  '__module__' : 'device_messages_pb2'
  # @@protoc_insertion_point(class_scope:DeviceId)
  })
_sym_db.RegisterMessage(DeviceId)

BootMessage = _reflection.GeneratedProtocolMessageType('BootMessage', (_message.Message,), {
  'DESCRIPTOR' : _BOOTMESSAGE,
  '__module__' : 'device_messages_pb2'
  # @@protoc_insertion_point(class_scope:BootMessage)
  })
_sym_db.RegisterMessage(BootMessage)

UartResponse = _reflection.GeneratedProtocolMessageType('UartResponse', (_message.Message,), {
  'DESCRIPTOR' : _UARTRESPONSE,
  '__module__' : 'device_messages_pb2'
  # @@protoc_insertion_point(class_scope:UartResponse)
  })
_sym_db.RegisterMessage(UartResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERSION._serialized_start=25
  _VERSION._serialized_end=97
  _DEVICEID._serialized_start=99
  _DEVICEID._serialized_end=148
  _BOOTMESSAGE._serialized_start=150
  _BOOTMESSAGE._serialized_end=252
  _UARTRESPONSE._serialized_start=254
  _UARTRESPONSE._serialized_end=313
# @@protoc_insertion_point(module_scope)
