# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uart_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13uart_messages.proto\"\x8f\x01\n\x07\x43ommand\x12 \n\x06\x62utton\x18\x01 \x01(\x0e\x32\x10.Command.Buttons\x12\r\n\x05value\x18\x02 \x01(\r\"S\n\x07\x42uttons\x12\r\n\tDoNothing\x10\x00\x12\x06\n\x02Up\x10\x01\x12\x08\n\x04\x44own\x10\x02\x12\t\n\x05Right\x10\x04\x12\x08\n\x04Left\x10\x03\x12\x08\n\x04Grab\x10\x05\x12\x08\n\x04Stop\x10\x06\"4\n\x05Reply\x12\r\n\x05x_pos\x18\x01 \x01(\x05\x12\r\n\x05y_pos\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x08\x62\x06proto3')



_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_COMMAND_BUTTONS = _COMMAND.enum_types_by_name['Buttons']
Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'uart_messages_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'uart_messages_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=24
  _COMMAND._serialized_end=167
  _COMMAND_BUTTONS._serialized_start=84
  _COMMAND_BUTTONS._serialized_end=167
  _REPLY._serialized_start=169
  _REPLY._serialized_end=221
# @@protoc_insertion_point(module_scope)
